### ISSUE TITLE
integrate lcs login

### ISSUE THREAD

**Issue by mjrb** [HackRU/helpq#2]
copy off of some other login meteor package to hack in lcs integration

**Comment by mjrb** [comment]
another good idea would be to explore making it a meteor package so it has potential for re usability

**Comment by hemangandhi** [comment]
https://github.com/HackRU/lcs/wiki/Using-LCS has some basic details... I'll fix it to link to the API docs (now that those exist). LMK what else I can do to make it easy.

**Comment by DonutsInBelly** [comment]
So it was discussed that we're using LCS login and then storing user data on Meteor's DB system - the only issue I can see here is if a user changes something with LCS, how does the Metoer DB get an update?

**Comment by mjrb** [comment]
done
