### ISSUE TITLE
volunteer/organizer login

### ISSUE THREAD

**Issue by mjrb** [HackRU/helpq#29]
view for volunteers/organizers to log in and see all tickets/see if tickets are getting served

**Comment by hemangandhi** [comment]
Can you please comment on https://github.com/HackRU/handbook/pull/74 if it's not noted there already.

**Comment by mjrb** [comment]
This specific issue doesn't have to do with vhx scheduler. It is just a more restricted version of the existing admin view

**Comment by hemangandhi** [comment]
I misread somehow... I'll just blame inebriation.

**Comment by mjrb** [comment]
we don't really need this
