### ISSUE TITLE
change copy to theme for HackRU

### ISSUE THREAD

**Issue by mjrb** [HackRU/helpq#3]
see HELPQREADME.md, also see constants.js
this will change the text of the application so things say HackRU mentor queue or something

**Comment by hemangandhi** [comment]
Pretty similar to #4

**Comment by mjrb** [comment]
Realistically I'll probably do this and #4 different days. Related to #4 : is there any existing styling can go off of? @hemanghandi

**Comment by mjrb** [comment]
done
